name: Publish to npm

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 14.15.1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Set up Node v${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Build and test"
        run: |
          npm ci
          npm run bundle
          npm test
      - name: "Publish to NPM if version changed"
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
